-- ══════════════════════════════════════════════════════
-- YuYu ↔ PIFA – Profiles-Tabelle
--
-- HISTORIE: Diese Datei hat ursprünglich eine eigene, schlanke profiles-Tabelle
-- (nur id/name/created_at) plus einen Auto-Anlage-Trigger auf auth.users definiert.
-- Es stellte sich heraus, dass "profiles" bereits von store-web/profiles-setup.sql
-- mit einer anderen, größeren Schema-Version angelegt wurde (id, name, age, email,
-- phone, bundesland, console, discipline - mehrere davon NOT NULL). CREATE TABLE
-- IF NOT EXISTS lief deshalb ins Leere, der Trigger blieb aber aktiv und versuchte
-- bei jedem neuen Signup nur (id, name) einzufügen - das verletzte die NOT-NULL-
-- Constraints und ließ JEDE Registrierung (egal über welche Oberfläche) mit einem
-- DB-Fehler abbrechen. Der Trigger wurde deshalb wieder entfernt:
--
--   DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
--   DROP FUNCTION IF EXISTS public.handle_new_user();
--
-- profiles-Zeilen werden stattdessen explizit beim Abschluss der Registrierung
-- angelegt (siehe store-web/src/pages/Register.tsx - upsert mit allen Pflicht-
-- feldern), genau wie es die PIFA-Mobile-App in Phase B auch tun wird. Das reicht
-- für confirmEmployerLink (App.jsx) aus, das nur auf profiles.name prüft, unabhängig
-- davon welche Oberfläche die Zeile geschrieben hat. Kein CREATE TABLE mehr hier -
-- die maßgebliche Definition ist store-web/profiles-setup.sql im pifa-Repo.
-- ══════════════════════════════════════════════════════
